version: '3.8'

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: contact-enrichment-searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - "4001:8080"  # Using 4001 to avoid conflicts with main Perplexica
    networks:
      - contact-enrichment-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/search?q=test&format=json"]
      interval: 30s
      timeout: 10s
      retries: 3

  contact-enrichment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contact-enrichment-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SEARXNG_URL=http://searxng:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    depends_on:
      searxng:
        condition: service_healthy
    networks:
      - contact-enrichment-network
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml:ro

networks:
  contact-enrichment-network:
    driver: bridge
