[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
NODE_ENV = "production"
PORT = { default = "3000" }
SEARXNG_URL = { default = "http://searxng-service.railway.internal:8080" }
# Add your API keys as Railway environment variables:
# OPENAI_API_KEY = "${{ OPENAI_API_KEY }}"
# GROQ_API_KEY = "${{ GROQ_API_KEY }}"
# ANTHROPIC_API_KEY = "${{ ANTHROPIC_API_KEY }}"
# GEMINI_API_KEY = "${{ GEMINI_API_KEY }}" 
