[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.searxng"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
PORT = { default = "8080" }
SEARXNG_SECRET = { default = "your-secret-key-here" }

[healthcheck]
path = "/search?q=test&format=json"
port = 8080 
